### PR TITLE
Solution for #9 - added regex validation for Phone Number field in UI…

### PR DESCRIPTION
**Pull request by sanjaypradeep**
1. Added Regex validation before we save information to DB.
2. Imported existing Modules from Django.
3. Error Message shown in UI whenever user fill irrelevant data to parent phone number. 
4. Tested different scenarios.

### CODE REVIEW

**Comment by sanjaypradeep** [comment]
Yep, thinking loud. But my suggestion would be, if we are based on country code, then better to have one more drop down near by, user need to select the country, accordingly the max length of field could be handled. 

hey but, what if we increase the size in regex which I've given? say `"^[0-9]{10,15}$`

**Comment by adigunsherif** [comment]
Yes please, let's do max of 15

**Comment by sanjaypradeep** [comment]
As discussed, committed the changes.

**Comment by adigunsherif** [comment]
Well done. merged and commited.

Thanks.

**Pull request merged**
